export enum ProjectStatus {
  IDEA = 'IDEA',
  PLANNING = 'PLANNING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  STUCK = 'STUCK'
}

export interface Task {
  id: string;
  title: string;
  description: string;
  isCompleted: boolean;
  estimatedTime?: string;
  category: 'Research' | 'Development' | 'Design' | 'Marketing' | 'Other';
}

export interface Project {
  id: string;
  title: string;
  description: string;
  status: ProjectStatus;
  createdAt: Date;
  tags: string[];
  tasks: Task[];
  imageUrl?: string; // Generated by AI
  notes: string;
}

export interface Message {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
  isStreaming?: boolean;
  groundingLinks?: Array<{title: string, uri: string}>;
}

export enum ViewState {
  DASHBOARD = 'DASHBOARD',
  PROJECT_DETAIL = 'PROJECT_DETAIL',
}